# Not used atm
version: "3.5"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped